---
title: "Open Scholarly Data @ SUB Göttingen - Overview"
format: 
  html:
    toc: true
    toc-location: left
    toc-title: Data
---

We use Google Big Query to work with large open scholarly data. Our main data sources are [Unpaywall](https://unpaywall.org), [Crossref](https://www.crossref.org) and [OpenAlex](https://openalex.org).

An overview of our data warehouse including procedures to load the data into BigQuery can be found below.

Anyone can view and query our publicly available [Open Scholarly Data  warehouse](https://console.cloud.google.com/bigquery?hl=en&project=subugoe-collaborative) on BigQuery with a [Google Cloud Computing account](https://cloud.google.com/). Note that Google will charge you for the number of bytes processed by each query (currently $ 6.25 per 1 TB). 

## Status Crossref

### Current Snapshot (cr_instant)


| Snapshot        | File            | Table               | Procedure | Last Changed | Coverage  | Number of rows |
|-----------------|-----------------|---------------------|-----------|--------------|-----------|-----------------|
|  2025/12        | all.json.tar.gz | [<nobr>cr_instant.snapshot</nobr>](https://console.cloud.google.com/bigquery?ws=!1m4!1m3!3m2!1ssubugoe-collaborative!2scr_instant) | [Repo](https://github.com/naustica/crossref_bq) |  12.01.2026  | All             | 177.533.594     |

: cr_instant {tbl-colwidths="[12,18,25,15,12,8,10]" .striped}



### Historical Snapshots (cr_history)

Info: Only includes publications with type 'journal-article'


| Snapshot        | File            | Table               | Procedure | Last Changed | Coverage  | Number of rows |
|-----------------|-----------------|---------------------|-----------|--------------|-----------|-----------------|
|  2018/04        | all.json.tar.gz | [<nobr>cr_history.cr_apr18</nobr>](https://console.cloud.google.com/bigquery?ws=!1m4!1m3!3m2!1ssubugoe-collaborative!2scr_history) | [Repo](https://github.com/naustica/crossref_bq) |  20.02.2022  | 2013-2018 | 16.766.035 |
|  2019/04        | all.json.tar.gz | [<nobr>cr_history.cr_apr19</nobr>](https://console.cloud.google.com/bigquery?ws=!1m4!1m3!3m2!1ssubugoe-collaborative!2scr_history) | [Repo](https://github.com/naustica/crossref_bq) |  29.10.2021  | 2013-2019 | 20.715.644 |
|  2020/04        | all.json.tar.gz | [<nobr>cr_history.cr_apr20</nobr>](https://console.cloud.google.com/bigquery?ws=!1m4!1m3!3m2!1ssubugoe-collaborative!2scr_history) | [Repo](https://github.com/naustica/crossref_bq) |  29.10.2021  | 2013-2020 | 25.334.525 |
|  2021/04        | all.json.tar.gz | [<nobr>cr_history.cr_apr21</nobr>](https://console.cloud.google.com/bigquery?ws=!1m4!1m3!3m2!1ssubugoe-collaborative!2scr_history) | [Repo](https://github.com/naustica/crossref_bq) |  29.10.2021  | 2013-2021 | 30.579.119 |
|  2022/04        | all.json.tar.gz | [<nobr>cr_history.cr_apr22</nobr>](https://console.cloud.google.com/bigquery?ws=!1m4!1m3!3m2!1ssubugoe-collaborative!2scr_history) | [Repo](https://github.com/naustica/crossref_bq) |  14.05.2022  | 2013-2022 | 35.939.195 |
|  2023/04        | all.json.tar.gz | [<nobr>cr_history.cr_apr23</nobr>](https://console.cloud.google.com/bigquery?ws=!1m4!1m3!3m2!1ssubugoe-collaborative!2scr_history) | [Repo](https://github.com/naustica/crossref_bq) |  07.05.2023  | 2013-2023 | 41.767.461 |
|  2024/04        | all.json.tar.gz | [<nobr>cr_history.cr_apr24</nobr>](https://console.cloud.google.com/bigquery?ws=!1m4!1m3!3m2!1ssubugoe-collaborative!2scr_history) | [Repo](https://github.com/naustica/crossref_bq) |  07.05.2024  | 2013-2024 | 47.709.184 |

: cr_history {tbl-colwidths="[12,18,25,15,12,8,10]" .striped}

## Status Unpaywall

### Current Snapshot (upw_instant)


| Snapshot| File                                          | Table                | Procedure | Last Changed | Coverage  | Number of rows |
|---------|-----------------------------------------------|----------------------|-----------|--------------|-----------|-----------------|
| 2024/11 | unpaywall_snapshot_2024-11-27T031702.jsonl.gz | [<nobr>upw_instant.snapshot</nobr>](https://console.cloud.google.com/bigquery?ws=!1m4!1m3!3m2!1ssubugoe-collaborative!2supw_instant) | [Repo](https://github.com/naustica/unpaywall_bq) | 23.06.2025 | 2008-2025 | 94.924.816 |

: upw_instant {tbl-colwidths="[10,25,22,13,12,8,10]" .striped}

### Historical Snapshots (upw_history)


| Snapshot| File                                          | Table                       | Procedure | Last Changed | Coverage  | Number of rows |
|---------|-----------------------------------------------|-----------------------------|-----------|--------------|-----------|-----------------|
| 2018/03 | unpaywall_snapshot_2018-03-29T113154.jsonl.gz | [<nobr>upw_history.upw_Mar18_08_20</nobr>](https://console.cloud.google.com/bigquery?ws=!1m4!1m3!3m2!1ssubugoe-collaborative!2supw_history) | [Repo](https://github.com/naustica/unpaywall_bq) |  29.10.2021  | 2008-2018 | 36.557.043 |
| 2019/02 | unpaywall_snapshot_2019-02-21T031509.jsonl.gz | [<nobr>upw_history.upw_Feb19_08_19</nobr>](https://console.cloud.google.com/bigquery?ws=!1m4!1m3!3m2!1ssubugoe-collaborative!2supw_history) | [Repo](https://github.com/naustica/unpaywall_bq) |  10.11.2021  | 2008-2019 | 42.143.979 |
| 2020/02 | unpaywall_snapshot_2020-02-25T115244.jsonl.gz | [<nobr>upw_history.upw_Feb20_08_20</nobr>](https://console.cloud.google.com/bigquery?ws=!1m4!1m3!3m2!1ssubugoe-collaborative!2supw_history) | [Repo](https://github.com/naustica/unpaywall_bq) |  30.10.2021  | 2008-2020 | 49.717.710 |
| 2021/02 | unpaywall_snapshot_2021-02-18T160139.jsonl.gz | [<nobr>upw_history.upw_Feb21_08_21</nobr>](https://console.cloud.google.com/bigquery?ws=!1m4!1m3!3m2!1ssubugoe-collaborative!2supw_history) | [Repo](https://github.com/naustica/unpaywall_bq) |  29.10.2021  | 2008-2021 | 58.437.927 |
| 2022/03 | unpaywall_snapshot_2022-03-09T083001.jsonl.gz | [<nobr>upw_history.upw_Mar22_08_22</nobr>](https://console.cloud.google.com/bigquery?ws=!1m4!1m3!3m2!1ssubugoe-collaborative!2supw_history) | [Repo](https://github.com/naustica/unpaywall_bq) |  14.03.2022 | 2008-2022 | 67.424.819 |

: upw_history {tbl-colwidths="[10,25,22,13,12,8,10]" .striped}

## Status Semantic Scholar 


| Snapshot   | Directory    | Table                | Procedure | Last Changed | Coverage  | Number of rows |
|------------|--------------|----------------------|-----------|--------------|-----------|-----------------|
| 2025-12-09 | papers/      | [<nobr>semantic_scholar.papers</nobr>](https://console.cloud.google.com/bigquery?ws=!1m4!1m3!3m2!1ssubugoe-collaborative!2ssemantic_scholar) | [Repo](https://github.com/naustica/semantic_scholar_bq) | 03.02.2026 | All | 231.081.324 |
| 2025-12-09 | venues/      | [<nobr>semantic_scholar.venues</nobr>](https://console.cloud.google.com/bigquery?ws=!1m4!1m3!3m2!1ssubugoe-collaborative!2ssemantic_scholar) | [Repo](https://github.com/naustica/semantic_scholar_bq) | 03.02.2026 | All | 194.578 |
| 2025-12-09 | abstracts/      | [<nobr>semantic_scholar.abstracts</nobr>](https://console.cloud.google.com/bigquery?ws=!1m4!1m3!3m2!1ssubugoe-collaborative!2ssemantic_scholar) | [Repo](https://github.com/naustica/semantic_scholar_bq) | 03.02.2026 | All | 36.867.403 |
| 2025-12-09 | citations/      | [<nobr>semantic_scholar.citations</nobr>](https://console.cloud.google.com/bigquery?ws=!1m4!1m3!3m2!1ssubugoe-collaborative!2ssemantic_scholar) | [Repo](https://github.com/naustica/semantic_scholar_bq) | 03.02.2026 | All | 2.918.533.428 |

: semantic_scholar {tbl-colwidths="[12,10,25,20,12,8,13]" .striped}

## Status OpenAlex


| Snapshot   | Directory     | Table                 | Procedure | Last Changed | Coverage  | Number of rows |
|------------|---------------|-----------------------|-----------|--------------|-----------|-----------------|
| 2025-09-30 | authors/      | [<nobr>openalex.authors</nobr>](https://console.cloud.google.com/bigquery?ws=!1m4!1m3!3m2!1ssubugoe-collaborative!2sopenalex)      | [Repo](https://github.com/naustica/openalex) |  16.10.2025  | All | 104.942.999 |
| 2025-10-01 | funders/      | [<nobr>openalex.funders</nobr>](https://console.cloud.google.com/bigquery?ws=!1m4!1m3!3m2!1ssubugoe-collaborative!2sopenalex)      | [Repo](https://github.com/naustica/openalex) |  16.10.2025  | All | 32.437 |
| 2025-10-01 | institutions/ | [<nobr>openalex.institutions</nobr>](https://console.cloud.google.com/bigquery?ws=!1m4!1m3!3m2!1ssubugoe-collaborative!2sopenalex) | [Repo](https://github.com/naustica/openalex) |  16.10.2025  | All | 117.731 |
| 2025-10-01 | publishers/   | [<nobr>openalex.publishers</nobr>](https://console.cloud.google.com/bigquery?ws=!1m4!1m3!3m2!1ssubugoe-collaborative!2sopenalex)   | [Repo](https://github.com/naustica/openalex) |  16.10.2025  | All | 10.741 |
| 2025-10-01 | sources/      | [<nobr>openalex.sources</nobr>](https://console.cloud.google.com/bigquery?ws=!1m4!1m3!3m2!1ssubugoe-collaborative!2sopenalex)      | [Repo](https://github.com/naustica/openalex) |  16.10.2025  | All | 260.787 |
| 2025-09-29 | topics/       | [<nobr>openalex.topics</nobr>](https://console.cloud.google.com/bigquery?ws=!1m4!1m3!3m2!1ssubugoe-collaborative!2sopenalex)       | [Repo](https://github.com/naustica/openalex) |  16.10.2025  | All | 4.516 |
| 2025-09-30 | works/        | [<nobr>openalex.works</nobr>](https://console.cloud.google.com/bigquery?ws=!1m4!1m3!3m2!1ssubugoe-collaborative!2sopenalex)        | [Repo](https://github.com/naustica/openalex) |  16.10.2025  | All | 271.335.309 |

: openalex {tbl-colwidths="[12,13,28,17,12,8,10]" .striped}

## Status OpenAlex-Walden


| Snapshot   | Directory     | Table                 | Procedure | Last Changed | Coverage  | Number of rows |
|------------|---------------|-----------------------|-----------|--------------|-----------|-----------------|
| 2026-01-14 | authors/      | [<nobr>openalex.authors</nobr>](https://console.cloud.google.com/bigquery?ws=!1m4!1m3!3m2!1ssubugoe-collaborative!2sopenalex_walden)      | [Repo](https://github.com/naustica/openalex) |  23.01.2026  | All | 106.100.192 |
| 2023-02-13 | funders/      | [<nobr>openalex.funders</nobr>](https://console.cloud.google.com/bigquery?ws=!1m4!1m3!3m2!1ssubugoe-collaborative!2sopenalex_walden)      | [Repo](https://github.com/naustica/openalex) |  23.01.2026  | All | 32.437 |
| 2026-01-14 | institutions/ | [<nobr>openalex.institutions</nobr>](https://console.cloud.google.com/bigquery?ws=!1m4!1m3!3m2!1ssubugoe-collaborative!2sopenalex_walden) | [Repo](https://github.com/naustica/openalex) |  23.01.2026  | All | 102.709 |
| 2024-11-25 | publishers/   | [<nobr>openalex.publishers</nobr>](https://console.cloud.google.com/bigquery?ws=!1m4!1m3!3m2!1ssubugoe-collaborative!2sopenalex_walden)   | [Repo](https://github.com/naustica/openalex) |  30.01.2026  | All | 10.703 |
| 2025-11-02 | sources/      | [<nobr>openalex.sources</nobr>](https://console.cloud.google.com/bigquery?ws=!1m4!1m3!3m2!1ssubugoe-collaborative!2sopenalex_walden)      | [Repo](https://github.com/naustica/openalex) |  23.01.2026  | All | 255.250 |
| 2024-12-04 | topics/       | [<nobr>openalex.topics</nobr>](https://console.cloud.google.com/bigquery?ws=!1m4!1m3!3m2!1ssubugoe-collaborative!2sopenalex_walden)       | [Repo](https://github.com/naustica/openalex) |  23.01.2026  | All | 4.516 |
| 2026-01-14 | works/        | [<nobr>openalex.works</nobr>](https://console.cloud.google.com/bigquery?ws=!1m4!1m3!3m2!1ssubugoe-collaborative!2sopenalex_walden)        | [Repo](https://github.com/naustica/openalex) |  23.01.2026  | All | 476.951.866 |

: openalex_walden {tbl-colwidths="[12,13,28,17,12,8,10]" .striped}

## Status OPENBIB


| Snapshot   | Table                 | Procedure | Last Changed | Coverage  | Number of rows |
|------------|-----------------------|-----------|--------------|-----------|-----------------|
| 2025-07-11 | [<nobr>openbib.publishers</nobr>](https://console.cloud.google.com/bigquery?ws=!1m4!1m3!3m2!1ssubugoe-collaborative!2sopenbib) | [Repo](https://github.com/kbopenbib/kbopenbib_data/) | 19.12.2025 | 2014-2025 | 379 |
| 2025-07-11 | [<nobr>openbib.publishers_relation</nobr>](https://console.cloud.google.com/bigquery?ws=!1m4!1m3!3m2!1ssubugoe-collaborative!2sopenbib) | [Repo](https://github.com/kbopenbib/kbopenbib_data/) | 19.12.2025 | 2014-2025 | 212 |
| 2025-07-11 | [<nobr>openbib.funding_information</nobr>](https://console.cloud.google.com/bigquery?ws=!1m4!1m3!3m2!1ssubugoe-collaborative!2sopenbib) | [Repo](https://github.com/kbopenbib/kbopenbib_data/) | 18.12.2025 | 2020-2025 | 16.902 |
| 2025-07-11 | [<nobr>openbib.document_types</nobr>](https://console.cloud.google.com/bigquery?ws=!1m4!1m3!3m2!1ssubugoe-collaborative!2sopenbib) | [Repo](https://github.com/kbopenbib/kbopenbib_data/) | 18.12.2025 | 2014-2025 | 61.495.813 |
| 2025-07-11 | [<nobr>openbib.kb_a_addr_inst</nobr>](https://console.cloud.google.com/bigquery?ws=!1m4!1m3!3m2!1ssubugoe-collaborative!2sopenbib) | [Repo](https://github.com/kbopenbib/kbopenbib_data/) | 18.12.2025 | All | 10.225.955 |
| 2025-07-11 | [<nobr>openbib.kb_s_addr_inst</nobr>](https://console.cloud.google.com/bigquery?ws=!1m4!1m3!3m2!1ssubugoe-collaborative!2sopenbib) | [Repo](https://github.com/kbopenbib/kbopenbib_data/) | 18.12.2025 | All | 10.227.010 |
| 2025-07-11 | [<nobr>openbib.kb_inst_lookup</nobr>](https://console.cloud.google.com/bigquery?ws=!1m4!1m3!3m2!1ssubugoe-collaborative!2sopenbib) | [Repo](https://github.com/kbopenbib/kbopenbib_data/) | 18.12.2025 | All | 2.363 |
| 2025-07-11 | [<nobr>openbib.kb_sector_lookup</nobr>](https://console.cloud.google.com/bigquery?ws=!1m4!1m3!3m2!1ssubugoe-collaborative!2sopenbib) | [Repo](https://github.com/kbopenbib/kbopenbib_data/) | 18.12.2025 | All | 22 |
| 2025-07-11 | [<nobr>openbib.jct_articles</nobr>](https://console.cloud.google.com/bigquery?ws=!1m4!1m3!3m2!1ssubugoe-collaborative!2sopenbib) | [Repo](https://github.com/kbopenbib/kbopenbib_data/) | 18.12.2025 | 2018-2025 | 2.898.386 |
| 2025-07-11 | [<nobr>openbib.jct_esac</nobr>](https://console.cloud.google.com/bigquery?ws=!1m4!1m3!3m2!1ssubugoe-collaborative!2sopenbib) | [Repo](https://github.com/kbopenbib/kbopenbib_data/) | 18.12.2025 | 2018-2025 | 1.445 |
| 2025-07-11 | [<nobr>openbib.jct_institutions</nobr>](https://console.cloud.google.com/bigquery?ws=!1m4!1m3!3m2!1ssubugoe-collaborative!2sopenbib) | [Repo](https://github.com/kbopenbib/kbopenbib_data/) | 18.12.2025 | 2018-2025 | 36.561 |
| 2025-07-11 | [<nobr>openbib.jct_journals</nobr>](https://console.cloud.google.com/bigquery?ws=!1m4!1m3!3m2!1ssubugoe-collaborative!2sopenbib) | [Repo](https://github.com/kbopenbib/kbopenbib_data/) | 18.12.2025 | 2018-2025 | 562.156 |
| 2025-07-11 | [<nobr>openbib.author_disambiguation_author_level</nobr>](https://console.cloud.google.com/bigquery?ws=!1m4!1m3!3m2!1ssubugoe-collaborative!2sopenbib) | [Repo](https://github.com/kbopenbib/kbopenbib_data/) | 26.01.2026 | 2000-2024 | 9.165.443 |
| 2025-07-11 | [<nobr>openbib.author_disambiguation_work_level</nobr>](https://console.cloud.google.com/bigquery?ws=!1m4!1m3!3m2!1ssubugoe-collaborative!2sopenbib) | [Repo](https://github.com/kbopenbib/kbopenbib_data/) | 26.01.2026 | 2000-2024 | 2.786.294 |

: openbib {tbl-colwidths="[12,35,23,12,8,10]" .striped}

## Status OpenAlex Document Type classification by SUB Göttingen

Info: Only includes publications with type 'article' or 'review' and primary source type 'journal'


| Snapshot   | Directory    | Table                | Procedure | Last Changed | Coverage  | Number of rows |
|------------|--------------|----------------------|-----------|--------------|-----------|-----------------|
| 2025-09-30 | works/       |<nobr> [resources.document_classification_september25</nobr>](https://console.cloud.google.com/bigquery?ws=!1m4!1m3!3m2!1ssubugoe-collaborative!2sresources) | [Repo](https://github.com/naustica/openalex_doctypes/tree/classifier/classifier) | 16.10.2025 | 2014-2025 | 62.841.950 |

: resources {tbl-colwidths="[12,10,30,25,12,11]" .striped}