---
title: "data checks"
format: html
---

```{r, echo = FALSE, message = FALSE, warning = FALSE}
knitr::opts_chunk$set(
  comment = "#>",
  collapse = TRUE,
  warning = FALSE,
  message = FALSE,
  echo = FALSE
)
options(scipen = 999, digits = 4)
knitr::knit_hooks$set(
  inline = function(x) {
    if (is.numeric(x)) {
      return(prettyNum(x, big.mark = ","))
    } else{
      return(x)
    }
  }
)
```

```{r, echo=FALSE,message = FALSE, warning = FALSE}
library(here)
library(DBI)
library(RPostgres)
library(tidyverse)
library(networkD3)
library(htmlwidgets)
library(htmltools)
library(sankeyD3) # Not on CRAN, but here <https://github.com/fbreitwieser/sankeyD3>
library(scales)
library(ggsci)
library(cowplot)
library(roadoi)
library(rcrossref)
```

# Verbindung zum KB

```{r}
kb_con <- dbConnect(RPostgres::Postgres(),
                    host = "biblio-p-db03.fiz-karlsruhe.de",
                    port = 6432,
                    dbname = "kbprod",
                    user =  Sys.getenv("kb_user"),
                    password = Sys.getenv("kb_pwd"),
                    bigint = "numeric")
```

# Anzahl an verloren gegangenen green tags via SQL berechnen

```{sql, connection=kb_con}
select sum(count) as total_count
from (
    select scp04_item_id, scp04_oa_status, scp07_oa_status, count(*) as count
    from unigsdoerner.scp_shared_corpus ssc
    where ssc.scp04_oa_status ~ 'repositoryvor|repositoryam' and ssc.scp07_oa_status !~ 'repositoryvor|repositoryam'
    group by scp04_item_id, scp04_oa_status, scp07_oa_status
) as subquery;
```

# fetch Unpaywall Info

```{r}
green_none_0407_raw <- oadoi_fetch(dois = doi_sample_0407, email = Sys.getenv("roadoi_email"), .progress = "text")
```


```{r}
load(here("_posts/scopus_oa_tagging_changes/data","green_none_0407_raw.RData"))
load(here("_posts/scopus_oa_tagging_changes/data","green_none_0710_raw.RData"))
```

```{r}
green_none_0407 <- green_none_0407_raw %>%
  select(doi, oa_status, has_repository_copy,oa_locations) %>%
  unnest(oa_locations, keep_empty = TRUE) %>%
  select(doi, oa_status, has_repository_copy, is_best, host_type)

write_csv(green_none_0407, here("_posts/scopus_oa_tagging_changes/data","green_none_0407.csv"))
```

```{r}
green_none_0710_raw <- oadoi_fetch(dois = doi_sample_0710, email = Sys.getenv("roadoi_email"), .progress = "text")

green_none_0710 <- green_none_0710_raw %>%
  select(doi, oa_status, has_repository_copy,oa_locations) %>%
  unnest(oa_locations, keep_empty = TRUE) %>%
  select(doi, oa_status, has_repository_copy, is_best, host_type)

write_csv(green_none_0710, here("_posts/scopus_oa_tagging_changes/data","green_none_0710.csv"))
```

# Unpaywall Info analysieren


```{r}
green_none_0407 %>%
  summarise(n=n_distinct(doi))

green_none_0407 %>%
  group_by(has_repository_copy) %>%
  summarise(n = n_distinct(doi))

green_none_0407 %>%
  filter(host_type == "repository") %>%
  group_by(oa_status, has_repository_copy, host_type) %>%
  summarise(n= n_distinct(doi)) %>%
  arrange(desc(n))
```

```{r}
upw_0407_recopy <- green_none_0407 %>%
  group_by(has_repository_copy) %>%
  summarise(count= n_distinct(doi)) %>%
  mutate(pct = format(round(count/sum(count) *100,2), nsmall = 2)) %>%
  arrange(desc(count))
```

```{r}
upw_0407_host <- green_none_0407 %>%
  group_by(oa_status,has_repository_copy,host_type) %>%
  summarise(count= n_distinct(doi)) %>%
  filter(host_type == "repository") %>%
  ungroup() %>%
  mutate(pct = format(round(count/sum(count) *100,2), nsmall = 2)) %>%
  arrange(desc(count))
```

```{r}
write_csv(upw_0407_recopy, here("_posts/scopus_oa_tagging_changes/data","upw_0407_recopy.csv"))
write_csv(upw_0407_host, here("_posts/scopus_oa_tagging_changes/data","upw_0407_host.csv"))
```


```{r}
green_none_0710 %>%
  summarise(n=n_distinct(doi))

green_none_0710 %>%
  group_by(has_repository_copy) %>%
  summarise(n = n_distinct(doi))

green_none_0710 %>%
  filter(host_type == "repository") %>%
  group_by(oa_status, has_repository_copy, host_type) %>%
  summarise(n= n_distinct(doi)) %>%
  arrange(desc(n))
```


```{r}
upw_0710_recopy <- green_none_0710 %>%
  group_by(has_repository_copy) %>%
  summarise(count= n_distinct(doi)) %>%
  mutate(pct = format(round(count/sum(count) *100,2), nsmall = 2)) %>%
  arrange(desc(count))
```

```{r}
upw_0710_host <- green_none_0710 %>%
  group_by(oa_status,has_repository_copy,host_type) %>%
  summarise(count= n_distinct(doi)) %>%
  filter(host_type == "repository") %>%
  ungroup() %>%
  mutate(pct = format(round(count/sum(count) *100,2), nsmall = 2)) %>%
  arrange(desc(count))
```


```{r}
write_csv(upw_0710_recopy, here("_posts/scopus_oa_tagging_changes/data","upw_0710_recopy.csv"))
write_csv(upw_0710_host, here("_posts/scopus_oa_tagging_changes/data","upw_0710_host.csv"))
```


# SQl Abfragen für den check der 10 dois gegen scp_rep

```{sql, connection=kb_con, output.var="kb_check_0407_bdb_raw"}
select i.item_id, i.doi, unnest(i.oa_status) as bdb_oa_status, rawdata.oa_status as rawdata_oa_status
from scp_b_202407.items i 
left join (select
	item_id,
	unnest(xpath('//xocs:oa-article-status/@free-to-read-status', xml_element, array[array['xocs', 'http://www.elsevier.com/xml/xocs/dtd']]))::text as "oa_status"
from (
	select item_id,
		unnest(xpath('/xocs:doc/xocs:meta/xocs:open-access/xocs:oa-article-status', 
		r.xml, 
		array[array['xocs', 'http://www.elsevier.com/xml/xocs/dtd']])) as xml_element
	from scp_rep_202407.repository r 
	where item_id in (
		select item_id  
		from scp_b_202407.items 
		where doi in ('10.1007/s11255-022-03188-3','10.1186/s12916-023-03072-6','10.15446/achsc.v47n2.86161','10.1038/s41598-023-40469-y','10.1109/tkde.2021.3112749','10.1111/jeu.12926','10.1016/j.jpedsurg.2022.03.034','10.1186/s12920-021-01105-8','10.1038/s41467-023-39992-3','10.1177/01925121231200124')
		)
) x) as rawdata 
on i.item_id = rawdata.item_id 
where i.item_id in (
		select item_id  
		from scp_b_202407.items 
		where doi in ('10.1007/s11255-022-03188-3','10.1186/s12916-023-03072-6','10.15446/achsc.v47n2.86161','10.1038/s41598-023-40469-y','10.1109/tkde.2021.3112749','10.1111/jeu.12926','10.1016/j.jpedsurg.2022.03.034','10.1186/s12920-021-01105-8','10.1038/s41467-023-39992-3','10.1177/01925121231200124')
		)
;
```

```{r}
kb_check_0407_oa_bdb_raw <- kb_check_0407_bdb_raw %>%
  select(bdb_oa_status,rawdata_oa_status)
```

```{r}
write_csv(kb_check_0407_oa_bdb_raw, here("_posts/scopus_oa_tagging_changes/data","kb_check_0407_oa_bdb_raw.csv"))
```


```{sql, connection=kb_con, output.var="kb_check_0710_bdb_raw"}
select i.item_id, i.doi, unnest(i.oa_status) as bdb_oa_status, rawdata.oa_status as rawdata_oa_status
from scp_b_202410.items i 
left join (select
	item_id,
	unnest(xpath('//xocs:oa-article-status/@free-to-read-status', xml_element, array[array['xocs', 'http://www.elsevier.com/xml/xocs/dtd']]))::text as "oa_status"
from (
	select item_id,
		unnest(xpath('/xocs:doc/xocs:meta/xocs:open-access/xocs:oa-article-status', 
		r.xml, 
		array[array['xocs', 'http://www.elsevier.com/xml/xocs/dtd']])) as xml_element
	from scp_rep_202410.repository r 
	where item_id in (
		select item_id  
		from scp_b_202410.items 
		where doi in ('10.1186/s12885-023-11645-0','10.18042/cepc/rdce.62.04','10.1021/acsomega.3c03246','10.4995/head22.2022.14555','10.5334/joc.226','10.1038/s41467-021-21580-y','10.1111/cdoe.12544','10.1016/j.jimed.2021.02.009','10.1155/2019/7639754','10.3390/dj7040104')
		)
) x) as rawdata 
on i.item_id = rawdata.item_id 
where i.item_id in (
		select item_id  
		from scp_b_202410.items 
		where doi in ('10.1186/s12885-023-11645-0','10.18042/cepc/rdce.62.04','10.1021/acsomega.3c03246','10.4995/head22.2022.14555','10.5334/joc.226','10.1038/s41467-021-21580-y','10.1111/cdoe.12544','10.1016/j.jimed.2021.02.009','10.1155/2019/7639754','10.3390/dj7040104')
		)
;
```

```{r}
kb_check_0710_oa_bdb_raw <- kb_check_0710_bdb_raw %>%
  select(bdb_oa_status,rawdata_oa_status)
```

```{r}
write_csv(kb_check_0710_oa_bdb_raw, here("_posts/scopus_oa_tagging_changes/data","kb_check_0710_oa_bdb_raw.csv"))
```

# Scopus Interface Check

```{r}
scp_interface <- read_csv(here("_posts/scopus_oa_tagging_changes/data","scp_interface_check.csv"))
```

```{r}
scp_interface_0407 <- scp_interface %>%
  filter(DOI %in% c('10.1007/s11255-022-03188-3','10.1186/s12916-023-03072-6','10.15446/achsc.v47n2.86161','10.1038/s41598-023-40469-y','10.1109/TKDE.2021.3112749','10.1111/jeu.12926','10.1016/j.jpedsurg.2022.03.034','10.1186/s12920-021-01105-8','10.1038/s41467-023-39992-3','10.1177/01925121231200124' )) %>%
  select(`Open Access`)
```

```{r}
scp_interface_0710 <- scp_interface %>%
  filter(DOI %in% c('10.1186/s12885-023-11645-0','10.18042/cepc/rdce.62.04','10.1021/acsomega.3c03246','10.4995/HEAd22.2022.14555','10.5334/joc.226','10.1038/s41467-021-21580-y','10.1111/cdoe.12544','10.1016/j.jimed.2021.02.009','10.1155/2019/7639754','10.3390/dj7040104')) %>%
  select(`Open Access`)
```

```{r}
write_csv(scp_interface_0407, here("_posts/scopus_oa_tagging_changes/data","scp_interface_0407.csv"))
write_csv(scp_interface_0710, here("_posts/scopus_oa_tagging_changes/data","scp_interface_0710.csv"))
```