---
title: "How we tried to make our data analysis reproducible"
description: |
  We conducted a data analysis investigating the open access (OA) uptake of German universities and non-university research institutions, taking into consideration the particular structure of the German research landscape. Based on several data sources we derived the OA share of their publication output, differentiating distinct OA types. In the spirit of good scientific practise and Open Science principles, we made an effort to ensure reproducibility of our empirical study. This report describes our line of action, why the result is still not thoroughly reproducible and the approach that we propose to address the open issues.
author:
  - name: Najko Jahn 
    url: https://twitter.com/najkoja
    affiliation: State and University Library Göttingen
    affiliation_url: https://www.sub.uni-goettingen.de/
  - name: Anne Hobert
    url: https://twitter.com/anhobert
    affiliation: State and University Library Göttingen
    affiliation_url: https://www.sub.uni-goettingen.de/
  - name: Maximilian Held
    affiliation: State and University Library Göttingen
    affiliation_url: https://www.sub.uni-goettingen.de/
date: 
creative_commons: CC BY
output: distill::distill_article
bibliography: pubs.bib
draft: true
---

```{r, echo = FALSE, message = FALSE, warning = FALSE}
knitr::opts_chunk$set(
  comment = "#>",
  collapse = TRUE,
  warning = FALSE,
  message = FALSE,
  echo = TRUE
)
```

  Within the framework of our BMBF funded research project [OAUNI - Open-access publication at universities in Germany: Development and influencing factors](https://www.wihoforschung.de/en/oauni-2182.php) we conducted a data analysis investigating the open access (OA) uptake of German universities and non-university research institutions, taking into consideration the particular structure of the German research landscape [@Hobert_2020]. We consulted the Web of Science in house instance of the [German Competence Center for Bibliometrics](http://www.forschungsinfo.de/Bibliometrie/en/index.php?id=home) in order to obtain the journal publications by authors affiliated with German research institutions which were published in the period from 2010 to 2018. From the ISSN-Gold-OA 3.0 list, provided by Bielefeld university [@Bruns_2019], and the OA discovery service [Unpaywall](https://unpaywall.org/), developed and maintained by the team of [Our Research](https://ourresearch.org/), we gathered information on their OA status. Using additionally [OpenDOAR](https://v2.sherpa.ac.uk/opendoar/) for a repository classification, we derived not only the overall OA share of individual institutions and research sectors but also prevalences of distinct OA types based on a systematic classification scheme. The analysis and the preparation of the submitted paper was based on RMarkdown, a dynamical report format that allowed us to integrate text as well as code chunks containing R, Phyton or sql code all into one document. 
  
  In the spirit of good scientific practise and Open Science principles, we made an effort to ensure that our empirical results are as reproducible as possible. Practical considerations also played a role since we expect us and colleagues to be able to work much more efficiently in future projects if our methods are documented openly and designed to be reused in other contexts. The first part of this report describes the line of action we took during the process of this data analysis. We illustrate why the result is still not thoroughly reproducible and what aspects can be improved. Secondly, we propose an approach that adresses the open issues and that we want to put into practise ourselves in the future. The main idea is to conduct package oriented research projects instead of focusing on (print-)papers as the primary research output of a study.
 
## Line of action 
 
 The scope of the [OAUNI project]((https://www.wihoforschung.de/en/oauni-2182.php)) is to investigate the development of the OA uptake of German reserach institutions and prevalences of specific types of OA publishing. In a second step, the aim is to identify explanatory factors (disciplinary and organisational) that influence the obtained OA shares and that can account for differences found in OA approaches of individual institutions. To this end, we collected the journal publication output of German universities and non-university research institutions from the  Web of Science in house instance of the [German Competence Center for Bibliometrics](http://www.forschungsinfo.de/Bibliometrie/en/index.php?id=home). The great advantage of this data source is the manually curated standardised affiliation information <!-- add citation?--> which allowed us to generate institution-specific publication portfolios as well as linking them to the associated sector (universities, non-university research institutes of the Helmholtz Association, Fraunhofer Society, Max Planck Society, Leibniz Association, and government research agencies) of the German research landscape.
 
 In an earlier study which we reported on in a seperate [blog post](https://subugoe.github.io/scholcomm_analytics/posts/unpaywall_evidence/) and in a talk given at last year's OA Tage [@Hobert_2019], we explored what kind of information on the OA status of publications is contained in the [Unpaywall](https://unpaywall.org/) data set. For the present study, we used that information in order to calculate the percentages of OA articles in the publication output of German research institutions. <!-- mention Big Query?--> Since Unpaywall's classification of OA types is based only on one available version found, the `best_oa_location`, we developed our own categorisation scheme that takes into account all freely available full text locations listed in Unpaywall. We additionally used the ISSN-Gold-OA 3.0 list to identify fully OA journals which were not classified as such within Unpaywall. For a more detailed distinction of different repository types, we matched domains of OA full text links stored in Unpaywall to repository domains in [OpenDOAR](https://v2.sherpa.ac.uk/opendoar/).
 
 In order to document the procedures of data gathering, processing and analysis we created a [GitHub repository](https://github.com/subugoe/oauni) which allowed us to collaborate on and version control our data base queries, codes and texts. We saved and tracked all sql-queries used to gather data from the Web of Science instance and the Big Query tables where we regularly import the recent Unpaywall data snapshots in order to efficiently access the contained data. 
 
 Initially, we classified the repository as private, intending to make it public at the time of publication of the study.
 
 Dashboard
 
 
 Remaining obstacles preventing thorough reproducibility:
 
 data: proprietary dataset, different aggregation levels
 
 scripts, not functions
 
## Future plans

muggle, package oriented research with executable papers as output
 
## Acknowledgments {.appendix}

<!-- coauthors of the paper, potentially proof-readers -->

We acknowledge financial support from the the Federal Ministry of Education and Research of Germany (BMBF) in the framework [Quantitative research on the science sector](https://www.wihoforschung.de/en/quantitative-research-on-the-science-sector-1573.php) (Project: "OAUNI Entwicklung und Einflussfaktoren des Open-Access-Publizierens an Universitäten in Deutschland", Förderkennzeichen: 01PU17023A).

